version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/services/glioblastoma-predictor"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/services/gromacs-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"
