export const TOKEN_PLANS = Object.freeze([
  {
    name: 'Trial',
    subtitle: 'Try the core workflow before purchasing credits',
    price: 0,
    credits: 4,
    description: 'A one-time starter allocation for a new account.',
    features: ['4 simulation credits', 'Low job priority', 'Most models and settings', 'Email support'],
    buttonText: 'Claim trial',
    buttonColor: 'gray',
  },
  {
    name: 'Standard',
    subtitle: 'For active research projects',
    price: 20,
    credits: 50,
    description: 'A one-time credit pack for routine exploration and validation.',
    features: ['50 simulation credits', 'Medium job priority', 'Most models and settings', 'Email support'],
    buttonText: 'Purchase',
    buttonColor: 'blue',
  },
  {
    name: 'Academic',
    subtitle: 'For larger academic workloads',
    price: 40,
    credits: 300,
    description: 'A one-time credit pack for sustained academic research.',
    features: ['300 simulation credits', 'Medium job priority', 'Most models and settings', 'Email support'],
    buttonText: 'Purchase',
    buttonColor: 'blue',
  },
  {
    name: 'Professional',
    subtitle: 'For demanding professional workloads',
    price: 80,
    credits: 720,
    description: 'A one-time credit pack with the highest self-serve allocation.',
    features: ['720 simulation credits', 'High job priority', 'All models and settings', 'Priority support', 'Commercial use'],
    buttonText: 'Purchase',
    buttonColor: 'purple',
  },
]);
